ARG POSTGRES_CLIENT_VERSION=9.6

FROM bbernhard/imagemonkey-buildbase:latest

ARG POSTGRES_CLIENT_VERSION

RUN echo "deb http://deb.debian.org/debian stretch main" >> /etc/apt/sources.list

RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
	&& wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

RUN apt-get update && apt-get install -y --no-install-recommends \
	postgresql-client-${POSTGRES_CLIENT_VERSION} \
	# until this pull request (https://github.com/h2non/bimg/pull/266) is merged and https://github.com/h2non/bimg/issues/269 is resolved, use the fork
	&& curl -s https://raw.githubusercontent.com/bbernhard/bimg/master/preinstall.sh | bash - \
	&& rm -rf /var/lib/apt/lists/*
