FROM golang:1.12.5-stretch

ARG MONKEY_DB_PASSWORD=""
ARG SENTRY_DSN=""
ARG X_CLIENT_ID=""
ARG X_CLIENT_SECRET=""
ARG JWT_SECRET=""
ARG IMAGE_DB_CONNECTION_STRING="user=monkey dbname=imagemonkey password=${MONKEY_DB_PASSWORD} sslmode=disable"

RUN apt-get update && apt-get install -y --no-install-recommends \
      sudo lsb-release

RUN mkdir -p /home/go/bin
ENV GOPATH=/home/go
ENV GOBIN=/home/go/bin

COPY src/web.go /tmp/src/web.go
COPY src/web_secrets.template /tmp/src/web_secrets.template
COPY src/auth.go /tmp/src/auth.go
COPY src/commons /tmp/src/commons
COPY src/image /tmp/src/image
COPY src/languages /tmp/src/languages
COPY src/database /tmp/src/database
COPY src/parser /tmp/src/parser
COPY src/datastructures /tmp/src/datastructures
COPY src/go.mod /tmp/src/go.mod
COPY src/go.sum /tmp/src/go.sum

# until this pull request (https://github.com/h2non/bimg/pull/266) is merged and https://github.com/h2non/bimg/issues/269 is resolved, use the fork
RUN curl -s https://raw.githubusercontent.com/bbernhard/bimg/master/preinstall.sh | bash -

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

RUN mv /tmp/src/web_secrets.template /tmp/src/web_secrets.go

RUN cd /tmp/src \
	&& go get -u -d gocv.io/x/gocv \
	&& cd /home/go/pkg/mod/gocv.io/x/gocv\@v0.20.0/ \
	&& make install
	
RUN cd /tmp/src/ \
	&& go get -d

RUN cd /tmp/src/ && go build -ldflags "-X main.SENTRY_DSN=$SENTRY_DSN -X main.IMAGE_DB_CONNECTION_STRING=$IMAGE_DB_CONNECTION_STRING -X main.X_CLIENT_SECRET=${X_CLIENT_SECRET}"

#RUN cd /tmp/src \
#	&& go build -ldflags "-X main.SENTRY_DSN=${SENTRY_DSN} -X main.IMAGE_DB_CONNECTION_STRING=$IMAGE_DB_CONNECTION_STRING -X main.X_CLIENT_SECRET=${X_CLIENT_SECRET} -X main.X_CLIENT_ID=$X_CLIENT_ID -X main.JWT_SECRET=${JWT_SECRET}" web.go auth.go web_secrets.go
