local animals = import 'animals.libsonnet';
local misc = import 'misc.libsonnet';
local autogenerated = import 'autogenerated.libsonnet';

local patch1 = std.mergePatch(misc, animals);
local total = std.mergePatch(patch1, autogenerated);

total
