local countries = import 'countries.libsonnet';
local misc = import 'misc.libsonnet';
local autogenerated = import 'autogenerated.libsonnet';

local patch1 = std.mergePatch(misc, countries);
local total = std.mergePatch(patch1, autogenerated);

total

