package main

import (
	log "github.com/sirupsen/logrus"
	commons "github.com/bbernhard/imagemonkey-core/commons"
)

func main() {
	autogeneratedBaseLabelsPath := "../wordlists/en/includes/labels/autogenerated"
	autogeneratedLabelsPath := autogeneratedBaseLabelsPath + ".libsonnet"
	autogeneratedBaseMetaLabelsPath := "../wordlists/en/includes/metalabels/autogenerated"
	autogeneratedMetaLabelsPath := autogeneratedBaseMetaLabelsPath + ".libsonnet"

	
	log.Info("Merging labels into one file...")
	labelsDirectoryMerger := commons.NewLabelsDirectoryMerger(autogeneratedBaseLabelsPath, autogeneratedLabelsPath)
	err := labelsDirectoryMerger.Merge()
	if err != nil {
		log.Fatal("Couldn't merge labels into one file: ", err.Error())
	}
	
	log.Info("Merging metalabels into one file...")
	metaLabelsDirectoryMerger := commons.NewMetaLabelsDirectoryMerger(autogeneratedBaseMetaLabelsPath, autogeneratedMetaLabelsPath)
	err = metaLabelsDirectoryMerger.Merge()
	if err != nil {
		log.Fatal("Couldn't merge metalabels into one file: ", err.Error())
	}


}
